name: release
permissions:
  contents: read
  id-token: write
  packages: write
on:
  push:
    tags:        
      - 'v*'
env:
  IMAGE_TAG: ${{ github.ref_name }}
  FRONTEND_IMAGE_NAME: backstage-frontend
  BACKEND_IMAGE_NAME: backstage-backend
jobs:
  build-push:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to ghcr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login \
              ghcr.io \
              -u $ \
              --password-stdin
      - name: build and push backend container image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }},ghcr.io/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE_NAME }}:latest"
      - name: build and push frontend container image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: Dockerfile.frontend
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }},ghcr.io/${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE_NAME }}:latest"
