name: ci
permissions:
  contents: read
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build-and-test-containers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install score-compose
        uses: score-spec/setup-score@v3
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
      - name: make compose-test
        run: |
          make compose-test
      - name: install score-k8s
        uses: score-spec/setup-score@v3
        with:
          file: score-k8s
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
      - name: make k8s-test
        run: |
          make kind-create-cluster
          make kind-load-images
          make k8s-test
